// Code generated by protoc-gen-wasmify-go. DO NOT EDIT.

package spanneranalyzer

import (
	"encoding/binary"
	"errors"
	"fmt"
	"math"
	"os"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"sync"

	"github.com/tyzerrr/spanneranalyzerwasm2go"
	"github.com/tyzerrr/spanneranalyzerwasm2go/base"
)

var (
	_ = binary.LittleEndian
	_ = errors.New
	_ = fmt.Errorf
	_ = math.Float32bits
	_ = os.Stderr
	_ = runtime.SetFinalizer
	_ = sort.Search
	_ = strconv.Itoa
	_ = strings.TrimSpace
	_ = sync.Once{}
	_ = wasm2go.Memory
	_ *base.Module
)

// pbNewBuf returns the scratch buffer every request marshal starts
// from. Starting from a presized slice instead of nil removes the
// append growth ladder (nil→8→16→… reallocations plus copies) that
// made runtime.growslice-under-pbAppendVarint 90% of one hot
// consumer's slice-growth profile; 64 bytes covers the dominant
// single-handle request shape (≤ 13 bytes) and small argument
// messages in one allocation. A sync.Pool variant was measured and
// REJECTED: the per-call Get/Put traffic and the pointer box each
// Put allocates cost more time than the saved reallocations
// (isolated A/B on googlesqlite's window suite: allocs/op −15% but
// sec/op +1.5%, B/op +4.8%).
func pbNewBuf() []byte { return make([]byte, 0, 64) }

// pbVarintLen reports the encoded size of v without writing it.
func pbVarintLen(v uint64) int {
	n := 1
	for v >= 0x80 {
		v >>= 7
		n++
	}
	return n
}

// pbAppendVarint appends a varint-encoded uint64.
func pbAppendVarint(buf []byte, v uint64) []byte {
	for v >= 0x80 {
		buf = append(buf, byte(v)|0x80)
		v >>= 7
	}
	return append(buf, byte(v))
}

// pbAppendTag appends a field tag.
func pbAppendTag(buf []byte, field, wireType uint32) []byte {
	return pbAppendVarint(buf, uint64(field<<3|wireType))
}

func pbAppendUint64(buf []byte, field uint32, v uint64) []byte {
	buf = pbAppendTag(buf, field, 0)
	return pbAppendVarint(buf, v)
}

func pbAppendInt32(buf []byte, field uint32, v int32) []byte {
	buf = pbAppendTag(buf, field, 0)
	return pbAppendVarint(buf, uint64(v))
}

func pbAppendInt64(buf []byte, field uint32, v int64) []byte {
	buf = pbAppendTag(buf, field, 0)
	return pbAppendVarint(buf, uint64(v))
}

func pbAppendBool(buf []byte, field uint32, v bool) []byte {
	buf = pbAppendTag(buf, field, 0)
	if v {
		return append(buf, 1)
	}
	return append(buf, 0)
}

func pbAppendString(buf []byte, field uint32, s string) []byte {
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(len(s)))
	return append(buf, s...)
}

func pbAppendBytes(buf []byte, field uint32, data []byte) []byte {
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(len(data)))
	return append(buf, data...)
}

func pbAppendFloat(buf []byte, field uint32, v float32) []byte {
	buf = pbAppendTag(buf, field, 5)
	var tmp [4]byte
	binary.LittleEndian.PutUint32(tmp[:], math.Float32bits(v))
	return append(buf, tmp[:]...)
}

func pbAppendDouble(buf []byte, field uint32, v float64) []byte {
	buf = pbAppendTag(buf, field, 1)
	var tmp [8]byte
	binary.LittleEndian.PutUint64(tmp[:], math.Float64bits(v))
	return append(buf, tmp[:]...)
}

func pbAppendSubmessage(buf []byte, field uint32, sub []byte) []byte {
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(len(sub)))
	return append(buf, sub...)
}

func pbAppendHandle(buf []byte, field uint32, ptr uint64) []byte {
	// The submessage has a fixed shape — tag(1,varint) + varint(ptr),
	// ≤ 11 bytes — so its length is computable up front and the
	// whole thing can be written straight into buf. The previous
	// shape built the inner bytes in a fresh slice per call
	// (`pbAppendUint64(nil, …)`), one heap allocation per handle
	// field on every bridge call.
	inner := 1 + pbVarintLen(ptr)
	buf = pbAppendTag(buf, field, 2)
	buf = pbAppendVarint(buf, uint64(inner))
	buf = append(buf, 0x08) // field 1, wire type varint
	return pbAppendVarint(buf, ptr)
}

// pbAppendHandlePtr is the nil-safe one-line wrapper around
// pbAppendHandle. Generic + comparable lets it accept any
// pointer-typed wrapper that provides rawPtr() and short-circuit
// when the pointer is nil. The caller writes
//
//	buf = pbAppendHandlePtr(buf, N, v.X)
//
// which gofmt keeps as one line; the alternative
//
//	if v.X != nil { buf = pbAppendHandle(buf, N, v.X.rawPtr()) }
//
// is gofmt-expanded to three lines per occurrence and accounts
// for several hundred KB of bloat across the binding.
func pbAppendHandlePtr[T interface {
	comparable
	rawPtr() uint64
}](buf []byte, field uint32, v T) []byte {
	var zero T
	if v == zero {
		return buf
	}
	return pbAppendHandle(buf, field, v.rawPtr())
}

// pbAppendSubmessagePtr is the value-type-message counterpart of
// pbAppendHandlePtr: nil-safe, gofmt-friendly one-liner around
// pbAppendSubmessage + the type's marshal() helper.
func pbAppendSubmessagePtr[T interface {
	comparable
	marshal() []byte
}](buf []byte, field uint32, v T) []byte {
	var zero T
	if v == zero {
		return buf
	}
	return pbAppendSubmessage(buf, field, v.marshal())
}

// clearPtrAny is the gofmt-friendly nil-safe ownership-transfer
// helper for handle parameters. Replaces the inline expansion
//
//	if c, ok := v.(interface{ clearPtr() }); ok { c.clearPtr() }
//
// (3 lines after gofmt) plus its surrounding nil-guard with a
// single function call. Handles both interface values
// (CatalogNode et al) and concrete pointers; the type assertion
// short-circuits when v is a true-nil interface, and the wrapped
// clearPtr() is itself nil-receiver-safe so a typed-nil pointer
// passed through the interface no-ops cleanly.
func clearPtrAny(v any) {
	if c, ok := v.(interface{ clearPtr() }); ok {
		c.clearPtr()
	}
}

// clearPtrAll is the slice variant of clearPtrAny. Used when the
// proto-field's wire shape is repeated-handle and the C++ side
// adopts ownership of every element. Each element runs through
// the same type-assertion shortcut so the helper handles
// concrete-pointer slices, interface slices, and slices that mix
// nil and non-nil entries uniformly.
func clearPtrAll[T any](items []T) {
	for _, item := range items {
		clearPtrAny(item)
	}
}

// pbReader is a streaming protobuf decoder.
type pbReader struct {
	data []byte
	pos  int
}

func (r *pbReader) hasData() bool { return r.pos < len(r.data) }

func (r *pbReader) readVarint() uint64 {
	var v uint64
	var shift uint
	for r.pos < len(r.data) {
		b := r.data[r.pos]
		r.pos++
		v |= uint64(b&0x7f) << shift
		if b < 0x80 {
			return v
		}
		shift += 7
	}
	return v
}

func (r *pbReader) next() (field, wireType uint32, ok bool) {
	if !r.hasData() {
		return 0, 0, false
	}
	tag := r.readVarint()
	return uint32(tag >> 3), uint32(tag & 7), true
}

func (r *pbReader) readString() string {
	n := int(r.readVarint())
	if r.pos+n > len(r.data) {
		n = len(r.data) - r.pos
	}
	s := string(r.data[r.pos : r.pos+n])
	r.pos += n
	return s
}

func (r *pbReader) readBytes() []byte {
	n := int(r.readVarint())
	if r.pos+n > len(r.data) {
		n = len(r.data) - r.pos
	}
	b := make([]byte, n)
	copy(b, r.data[r.pos:r.pos+n])
	r.pos += n
	return b
}

func (r *pbReader) readBool() bool {
	return r.readVarint() != 0
}

func (r *pbReader) readInt32() int32 {
	return int32(r.readVarint())
}

func (r *pbReader) readInt64() int64 {
	return int64(r.readVarint())
}

func (r *pbReader) readUint32() uint32 {
	return uint32(r.readVarint())
}

func (r *pbReader) readUint64() uint64 {
	return r.readVarint()
}

func (r *pbReader) readFloat() float32 {
	if r.pos+4 > len(r.data) {
		r.pos = len(r.data)
		return 0
	}
	v := binary.LittleEndian.Uint32(r.data[r.pos : r.pos+4])
	r.pos += 4
	return math.Float32frombits(v)
}

func (r *pbReader) readDouble() float64 {
	if r.pos+8 > len(r.data) {
		r.pos = len(r.data)
		return 0
	}
	v := binary.LittleEndian.Uint64(r.data[r.pos : r.pos+8])
	r.pos += 8
	return math.Float64frombits(v)
}

func (r *pbReader) readSubmessage() *pbReader {
	n := int(r.readVarint())
	if r.pos+n > len(r.data) {
		n = len(r.data) - r.pos
	}
	sub := &pbReader{data: r.data[r.pos : r.pos+n]}
	r.pos += n
	return sub
}

func (r *pbReader) skip(wireType uint32) {
	switch wireType {
	case 0: // varint
		r.readVarint()
	case 1: // 64-bit
		r.pos += 8
	case 2: // length-delimited
		n := int(r.readVarint())
		r.pos += n
	case 5: // 32-bit
		r.pos += 4
	}
	if r.pos > len(r.data) {
		r.pos = len(r.data)
	}
}

// pbExtractError scans a response for field 15 (error string).
func pbExtractError(resp []byte) error {
	r := &pbReader{data: resp}
	for f, w, ok := r.next(); ok; f, w, ok = r.next() {
		if f == 15 {
			return errors.New(r.readString())
		}
		r.skip(w)
	}
	return nil
}

// readHandlePtr reads the ptr from a response. Handles two patterns:
// 1. Direct varint: field 1, wireType 0 → read varint directly
// 2. Submessage: field 1, wireType 2 → read submessage, then field 1 varint inside
func readHandlePtr(data []byte) uint64 {
	r := &pbReader{data: data}
	for f, w, ok := r.next(); ok; f, w, ok = r.next() {
		if f == 1 {
			if w == 0 {
				// Direct varint (constructor pattern)
				return r.readVarint()
			}
			if w == 2 {
				// Submessage (write_handle pattern)
				sub := r.readSubmessage()
				for sf, sw, sok := sub.next(); sok; sf, sw, sok = sub.next() {
					if sf == 1 && sw == 0 {
						return sub.readVarint()
					}
					sub.skip(sw)
				}
			}
			return 0
		}
		r.skip(w)
	}
	return 0
}

// readPtrAtField returns the handle pointer encoded at response field f.
// f == 1 takes the fast path via readHandlePtr (which already handles
// both the direct-varint constructor shape and the submessage write_handle
// shape); other fields are walked once to find the correct submessage.
// Returns 0 if the field is not present, which is the standard "absent
// handle" sentinel — callers translate that to (nil, nil).
func readPtrAtField(resp []byte, f uint32) uint64 {
	if f == 1 {
		return readHandlePtr(resp)
	}
	pr := &pbReader{data: resp}
	for ff, w, ok := pr.next(); ok; ff, w, ok = pr.next() {
		if ff == f {
			if w == 2 {
				sub := pr.readSubmessage()
				return readHandlePtr(sub.data)
			}
			return 0
		}
		pr.skip(w)
	}
	return 0
}

// decodeChildHandle is the standard accessor-return shape. It reads
// the handle pointer at field f, returns nil for missing/zero, and
// otherwise constructs the child via ctor and pins the parent (owner)
// onto it via setKeepAlive when owner is non-nil. Constructor-style
// callers (free functions) pass owner=nil; accessors pass the
// receiver. The child must already implement the unexported keepAlive
// interface, which every generated handle struct does.
func decodeChildHandle[T any](resp []byte, field uint32, owner any, ctor func(uint64) *T) *T {
	ptr := readPtrAtField(resp, field)
	if ptr == 0 {
		return nil
	}
	child := ctor(ptr)
	if owner != nil {
		if ka, ok := any(child).(interface{ setKeepAlive(any) }); ok {
			ka.setKeepAlive(owner)
		}
	}
	return child
}

// decodeAbstractAs is the abstract-return counterpart of
// decodeChildHandle: read field f, look up the runtime concrete type
// via resolveAbstractHandle, type-assert to I, attach keepAlive when
// owner is non-nil. ifaceName is only used in the error message when
// the runtime type does not satisfy I (which is a real bug, not a
// "missing field" condition).
func decodeAbstractAs[I any](resp []byte, field uint32, owner any, ifaceName string) (I, error) {
	var z I
	ptr := readPtrAtField(resp, field)
	if ptr == 0 {
		return z, nil
	}
	resolved, err := resolveAbstractHandle(ptr)
	if err != nil {
		return z, err
	}
	if v, ok := resolved.(I); ok {
		if owner != nil {
			if ka, okKA := any(v).(interface{ setKeepAlive(any) }); okKA {
				ka.setKeepAlive(owner)
			}
		}
		return v, nil
	}
	return z, fmt.Errorf("resolved type %T does not implement %s", resolved, ifaceName)
}

// readScalarAtField walks resp once for field f and reads the value via
// the read closure. Missing field returns the zero value. The closure is
// always one of (*pbReader).readBool / readInt32 / readInt64 / readUint32
// / readUint64 / readFloat / readDouble / readString / readBytes - small
// values, but they fold the per-method scan-and-read loop into one call
// site.
func readScalarAtField[T any](resp []byte, f uint32, read func(*pbReader) T) T {
	var z T
	pr := &pbReader{data: resp}
	for ff, w, ok := pr.next(); ok; ff, w, ok = pr.next() {
		if ff == f {
			return read(pr)
		}
		pr.skip(w)
	}
	return z
}

// factoryFor curries a typed constructor (newXNoFinalizer) into the
// untyped factory shape stored in cppTypeFactories. Without it the
// generated cppTypeToGoType map had to repeat
//
//	"googlesql::Foo": func(ptr uint64) any { return newFooNoFinalizer(ptr) }
//
// per concrete type — ~1,400 structurally-identical closures.
func factoryFor[T any](ctor func(uint64) *T) func(uint64) any {
	return func(ptr uint64) any { return ctor(ptr) }
}

// enumString backs the per-enum String() methods. Generated code emits
// parallel _vals_<E> []int32 and _names_<E> []string slices keyed in
// canonical order; this helper does a linear scan and falls back to
// the decimal form for values that aren't in the table (forward
// compatibility when new values land before regeneration).
func enumString(v int32, vals []int32, names []string) string {
	for i, x := range vals {
		if x == v {
			return names[i]
		}
	}
	return strconv.Itoa(int(v))
}

var _ = errors.New
var _ = binary.LittleEndian
var _ = fmt.Errorf
var _ = math.Float32bits
var _ = strconv.Itoa

// Module is the bridge handle. It wraps the wasm2go-transpiled module
// (*base.Module) and serialises every entry on m.mu.
//
// Reentrant callbacks — a host-import callback whose handler needs
// to make further calls back into the transpiled module — are
// supported by releasing m.mu around the user handler in
// handleCallback.
//
// Safety rests on a single structural property: every path that
// touches transpiled module state goes through m.invoke, and
// m.invoke holds m.mu for the entire duration of its call. The
// release window in handleCallback simply lets another m.invoke
// grab the mutex and run as a fully nested top-level call — same
// goroutine via the user handler, different goroutine via an
// unrelated caller, it doesn't matter. Either way the nested call
// enters, balances its own state changes, and exits before the
// outer call resumes, so the outer call never observes a mid-flight
// inner call.
type Module struct {
	// mu serialises every entry into the transpiled module (invoke +
	// nested re-entry from inside a callback handler).
	mu sync.Mutex
	g  *base.Module
	// cbMu guards callbacks and nextCBID. RWMutex because lookup in
	// handleCallback is hot (every host-import dispatch) while
	// Register/Unregister are rare (typically once per lifetime of a
	// registered Go-side handler). Held only for the brief map op;
	// never held while running user code or the transpiled module,
	// so it never participates in the m.mu -> transpiled-module ->
	// handleCallback chain and cannot deadlock against it.
	cbMu      sync.RWMutex
	callbacks map[int32]CallbackHandler
	nextCBID  int32
	// cbDesc is the reusable guest-memory result descriptor for callback
	// returns on a memory64 module (see encodeCallbackResult); 0 until
	// first use, and never touched on wasm32.
	cbDesc wptr
}

// wptr is the guest pointer width: int32 for a wasm32 module, int64
// for a memory64 (wasm64) one. Every pointer or length that crosses
// the bridge boundary is a wptr; the transpiled wasm2go package's
// export/import signatures use the same width, so the two packages
// stay in lock-step from the one substitution the generator makes.
type wptr = int32

var (
	globalModule *Module
	initOnce     sync.Once
	initErr      error
)

// CallbackHandler is implemented by Go types that need to be called from C++.
// The type is always defined (the Module struct references it); the
// registration/dispatch machinery is only emitted when the wasm imports
// wasmify.callback_invoke.
type CallbackHandler interface {
	HandleCallback(methodID int32, req []byte) ([]byte, error)
}

// Options configure the module the generated API runs on. The zero
// value is what Init uses: the default WASI implementation (the host
// filesystem, environment and stdio), the engine's own initial memory
// reservation, and its wasm32 4 GiB ceiling.
type Options struct {
	// WASI replaces the wasi_snapshot_preview1 implementation the guest
	// runs against. base.DefaultWASI() returns the default one, whose
	// setters scope the filesystem to a directory (or an arbitrary
	// base.FS), replace the environment and redirect stdio; any
	// implementation of the interface will do. nil keeps the default.
	WASI base.Wasi_snapshot_preview1Imports

	// MemoryReserveBytes pre-reserves linear memory. A guest that grows
	// to a size known up front — loading a large model or data file —
	// otherwise reallocates and copies the whole linear memory as it
	// goes. Zero keeps the engine's default headroom.
	MemoryReserveBytes int

	// MaxMemoryBytes caps linear-memory growth, so a workload bigger
	// than expected fails inside the guest (memory.grow returns -1)
	// instead of growing the host process. Zero keeps the engine's own
	// ceiling.
	MaxMemoryBytes uint64
}

// Init initializes the global module with the default Options. Must be
// called before any API use. Safe to call multiple times (uses
// sync.Once).
func Init() error { return InitWith(Options{}) }

// InitWith initializes the global module with opts. Like Init it runs at
// most once per process: the module owns one linear memory and one C
// heap, so there is exactly one instance and the first initialization
// wins. A later call — with any Options — returns that instance's
// initialization result without reconfiguring it.
func InitWith(opts Options) error {
	initOnce.Do(func() {
		initErr = initModule(opts)
	})
	return initErr
}

// module returns the initialized global module. Panics if Init was not
// called.
func module() *Module {
	if globalModule == nil {
		panic("wasmify: Init() must be called before using any API")
	}
	return globalModule
}

// Instance returns the transpiled module the global API runs on, or nil
// before initialization.
//
// It exists for base.AccessMemory, which is the only safe way to read or
// write linear memory from a goroutine other than the one running a call
// — an interrupt flag an embedder raises while a long call is in flight,
// a progress word it polls. Everything else should go through the
// generated API: calling into the module directly bypasses the lock that
// serialises entries and the C stack would be shared with the call in
// progress.
func Instance() *base.Module {
	if globalModule == nil {
		return nil
	}
	return globalModule.g
}

func initModule(opts Options) (retErr error) {
	m := &Module{}
	env := envStubs{m: m}
	wasi := opts.WASI
	if wasi == nil {
		wasi = base.DefaultWASI()
	}
	if opts.MemoryReserveBytes > 0 {
		m.g = wasm2go.NewWithWASIReserve(wasi, env, opts.MemoryReserveBytes)
	} else {
		m.g = wasm2go.NewWithWASI(wasi, env)
	}
	if opts.MaxMemoryBytes > 0 {
		wasm2go.SetMaxMemory(m.g, opts.MaxMemoryBytes)
	}
	// Set globalModule eagerly so the rest of the API can run even if
	// _initialize panics partway through C++ static-initializer code.
	globalModule = m
	defer func() {
		if r := recover(); r != nil {
			retErr = fmt.Errorf("init panicked: %v", r)
		}
	}()
	wasm2go.Initialize(m.g)
	_ = wasm2go.WasmInit(m.g)
	return nil
}

// invoke serializes req into wasm memory, runs the per-export caller
// (wasm2go.Inv_<svc>_<mt>), and unpacks the response via decodeResult.
// call is the trap-safe per-export entry point: it snapshots and
// restores the mutable wasm globals so a mid-call panic does not leak
// an abandoned C++ activation frame.
func (m *Module) invoke(serviceID, methodID int32, req []byte, call func(*base.Module, wptr, wptr) (int64, error)) ([]byte, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	var reqPtr, reqLen wptr
	if len(req) > 0 {
		reqPtr = wasm2go.WasmAlloc(m.g, wptr(len(req)))
		reqLen = wptr(len(req))
		// Free reqPtr unconditionally on return so the request
		// buffer never lingers in wasm memory when the call traps
		// or the early-exit branches below fire. Guard against
		// the WasmAlloc-returned-zero case: free(NULL) is a
		// dlmalloc no-op but C++ allocators are less consistent.
		if reqPtr != 0 {
			defer wasm2go.WasmFree(m.g, reqPtr)
		}
		copy(wasm2go.Memory(m.g)[wptrOff(reqPtr):], req)
	}
	packed, err := call(m.g, reqPtr, reqLen)
	if err != nil {
		return nil, err
	}
	respPtr, respLen := decodeResult(m.g, packed)
	if respLen == 0 {
		return nil, nil
	}
	mem := wasm2go.Memory(m.g)
	out := make([]byte, respLen)
	copy(out, mem[respPtr:respPtr+respLen])
	wasm2go.WasmFree(m.g, wptr(respPtr))
	return out, nil
}

// resolveTypeName calls the C++ bridge to get the runtime type name of
// the object at ptr. Returns a fully qualified C++ class name.
func (m *Module) resolveTypeName(ptr uint64) (string, error) {
	buf := pbAppendUint64(pbNewBuf(), 1, ptr)
	m.mu.Lock()
	defer m.mu.Unlock()
	reqPtr := wasm2go.WasmAlloc(m.g, wptr(len(buf)))
	copy(wasm2go.Memory(m.g)[wptrOff(reqPtr):], buf)
	packed := wasm2go.WasmifyGetTypeName(m.g, reqPtr, wptr(len(buf)))
	respPtr, respLen := decodeResult(m.g, packed)
	defer wasm2go.WasmFree(m.g, reqPtr)
	if respLen == 0 {
		return "", nil
	}
	resp := make([]byte, respLen)
	copy(resp, wasm2go.Memory(m.g)[respPtr:respPtr+respLen])
	defer wasm2go.WasmFree(m.g, wptr(respPtr))
	if e := pbExtractError(resp); e != nil {
		return "", e
	}
	r := &pbReader{data: resp}
	for f, w, ok := r.next(); ok; f, w, ok = r.next() {
		if f == 1 {
			return r.readString(), nil
		}
		r.skip(w)
	}
	return "", nil
}

// invokeMethod fans the wasm call out into the runtime, then folds in
// the (very common) pbExtractError check on the response. call is the
// per-export wasm2go.Inv_<svc>_<mt> entry point.
func invokeMethod(svc, mid int32, req []byte, call func(*base.Module, wptr, wptr) (int64, error)) ([]byte, error) {
	resp, err := module().invoke(svc, mid, req, call)
	if err != nil {
		return nil, err
	}
	if e := pbExtractError(resp); e != nil {
		return nil, e
	}
	return resp, nil
}

// wptrOff widens a guest pointer to an unsigned slice offset. wasm32
// pointers are UNSIGNED i32s: past the 2 GiB line the bit pattern is
// negative in Go, so a signed slice index would panic.
func wptrOff(p wptr) uint64 {
	return uint64(uint32(p))
}

func decodeResult(_ *base.Module, packed int64) (uint64, uint64) {
	return uint64(packed) >> 32, uint64(packed) & 0xFFFFFFFF
}

func encodeCallbackResult(m *Module, resp []byte) int64 {
	ptr := wasm2go.WasmAlloc(m.g, wptr(len(resp)))
	copy(wasm2go.Memory(m.g)[wptrOff(ptr):], resp)
	return int64(ptr)<<32 | int64(len(resp))
}

// envStubs implements wasm2go/base.EnvImports — the host side of the
// wasm "env" imports. The per-method definitions are emitted by the
// generator (generateEnvStubs) since the import set is module-specific.
type envStubs struct{ m *Module }

func (h envStubs) Emscripten_pc_get_function(m *base.Module, l0 int32) int32 { return 0 }
func (h envStubs) Emscripten_stack_snapshot(m *base.Module) int32            { return 0 }
func (h envStubs) Emscripten_stack_unwind_buffer(m *base.Module, l0 int32, l1 int32, l2 int32) int32 {
	return 0
}
func (h envStubs) X_ZN4absl12lts_2026010712log_internal12ExitOnDFatalEv(m *base.Module) int32 {
	return 0
}
func (h envStubs) X_ZN4absl12lts_2026010712log_internal13IsInitializedEv(m *base.Module) int32 {
	return 0
}
func (h envStubs) X_ZN4absl12lts_2026010712log_internal13WriteToStderrENSt3__217basic_string_viewIcNS2_11char_traitsIcEEEENS0_11LogSeverityE(m *base.Module, l0 int32, l1 int32) {
}
func (h envStubs) X_ZN4absl12lts_2026010712log_internal24MaxFramesInLogStackTraceEv(m *base.Module) int32 {
	return 0
}
func (h envStubs) X_ZN4absl12lts_2026010712log_internal24SetSuppressSigabortTraceEb(m *base.Module, l0 int32) int32 {
	return 0
}
func (h envStubs) X_ZN4absl12lts_2026010712log_internal28ShouldSymbolizeLogStackTraceEv(m *base.Module) int32 {
	return 0
}
func (h envStubs) X_ZN4absl12lts_2026010712log_internal8TimeZoneEv(m *base.Module) int32 { return 0 }
func (h envStubs) X_ZN4absl12lts_2026010713time_internal4cctz12TimeZoneLibC4MakeERKNSt3__212basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE(m *base.Module, l0 int32) int32 {
	return 0
}
func (h envStubs) X_ZN4absl12lts_2026010716raw_log_internal6RawLogENS0_11LogSeverityEPKciS4_z(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32) {
}
func (h envStubs) X_ZN6google7spanner8emulator7backend17RemoteUdfProtocol11FingerprintEN4absl12lts_202601074SpanIKN9googlesql5ValueEEE(m *base.Module, l0 int32, l1 int32) {
}
func (h envStubs) X_ZN6google7spanner8emulator7backend17RemoteUdfProtocol6ToJsonERKN9googlesql5ValueE(m *base.Module, l0 int32, l1 int32) {
}
func (h envStubs) X_ZN6google7spanner8emulator7backend17RemoteUdfProtocol7ToValueEN9googlesql17JSONValueConstRefEPKNS4_4TypeE(m *base.Module, l0 int32, l1 int32, l2 int32) {
}
func (h envStubs) X_ZN6google7spanner8emulator7backend17RemoteUdfProtocol7ToValueEyPKN9googlesql4TypeE(m *base.Module, l0 int32, l1 int64, l2 int32) {
}
func (h envStubs) X_ZN6google7spanner8emulator7backend18RemoteUdfEvaluator14BuildEvaluatorENSt3__212basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEESA_PKN9googlesql4TypeE(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) {
}
func (h envStubs) X_ZN6google7spanner8emulator7backend18RemoteUdfEvaluator22EvaluateRemoteFunctionENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_N4absl12lts_202601074SpanIKN9googlesql5ValueEEE(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) {
}
func (h envStubs) X_ZN9googlesql14FirstCharLowerENSt3__217basic_string_viewIcNS0_11char_traitsIcEEEE(m *base.Module, l0 int32, l1 int32) {
}
func (h envStubs) X_ZN9googlesql15GetErrorSourcesERKN4absl12lts_202601076StatusE(m *base.Module, l0 int32, l1 int32) {
}
func (h envStubs) X_ZN9googlesql15MakeErrorSourceERKN4absl12lts_202601076StatusENSt3__217basic_string_viewIcNS5_11char_traitsIcEEEENS_16ErrorMessageModeE(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32) {
}
func (h envStubs) X_ZN9googlesql20ShouldPropagateErrorERKN4absl12lts_202601076StatusE(m *base.Module, l0 int32) int32 {
	return 0
}
func (h envStubs) X_ZN9googlesql22EvaluateQuantifiedLikeERKNS_30QuantifiedLikeEvaluationParamsE(m *base.Module, l0 int32, l1 int32) {
}
func (h envStubs) X_ZN9googlesql24TokenListFromStringArrayENSt3__26vectorINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS5_IS7_EEEEb(m *base.Module, l0 int32, l1 int32, l2 int32) {
}
func (h envStubs) X_ZN9googlesql28RegisterBuiltinJsonFunctionsEv(m *base.Module)  {}
func (h envStubs) X_ZN9googlesql28RegisterBuiltinUuidFunctionsEv(m *base.Module)  {}
func (h envStubs) X_ZN9googlesql29RegisterBuiltinRangeFunctionsEv(m *base.Module) {}
func (h envStubs) X_ZN9googlesql29StatusesToDeprecationWarningsEN4absl12lts_202601074SpanIKNS1_6StatusEEENSt3__217basic_string_viewIcNS6_11char_traitsIcEEEE(m *base.Module, l0 int32, l1 int32, l2 int32) {
}
func (h envStubs) X_ZN9googlesql31GetDefaultErrorMessageStabilityEv(m *base.Module) int32 { return 0 }
func (h envStubs) X_ZN9googlesql31StatusWithInternalErrorLocationERKN4absl12lts_202601076StatusERKNS_18ParseLocationPointE(m *base.Module, l0 int32, l1 int32, l2 int32) {
}
func (h envStubs) X_ZN9googlesql32DeprecationWarningsToDebugStringEN4absl12lts_202601074SpanIKNS_30FreestandingDeprecationWarningEEE(m *base.Module, l0 int32, l1 int32) {
}
func (h envStubs) X_ZN9googlesql8internal15GetPublicSuffixENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(m *base.Module, l0 int32, l1 int32) {
}
func (h envStubs) X_ZN9googlesql8internal19GetTopPrivateDomainENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(m *base.Module, l0 int32, l1 int32) {
}
func (h envStubs) X_ZN9googlesql9functions12ZstdCompressENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEEx(m *base.Module, l0 int32, l1 int32, l2 int64) {
}
func (h envStubs) X_ZN9googlesql9functions14ZstdDecompressENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEEbx(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int64) {
}
func (h envStubs) X_ZN9googlesql9functions15FarmFingerprintENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(m *base.Module, l0 int32) int64 {
	return 0
}
func (h envStubs) X_ZN9googlesql9functions22SplitUtf8WithCollationERKNS_17GoogleSqlCollatorENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_PNS4_6vectorIS8_NS4_9allocatorIS8_EEEEPN4absl12lts_202601076StatusE(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32) int32 {
	return 0
}
func (h envStubs) X_ZN9googlesql9functions24ReplaceUtf8WithCollationERKNS_17GoogleSqlCollatorENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_S8_PNS4_12basic_stringIcS7_NS4_9allocatorIcEEEEPN4absl12lts_202601076StatusE(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32, l5 int32) int32 {
	return 0
}
func (h envStubs) X_ZN9googlesql9functions24SplitSubstrWithCollationERKNS_17GoogleSqlCollatorENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_xxPNS4_12basic_stringIcS7_NS4_9allocatorIcEEEE(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int64, l5 int64, l6 int32) {
}
func (h envStubs) X_ZN9googlesql9functions25EndsWithUtf8WithCollationERKNS_17GoogleSqlCollatorENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_PbPN4absl12lts_202601076StatusE(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32) int32 {
	return 0
}
func (h envStubs) X_ZN9googlesql9functions27StartsWithUtf8WithCollationERKNS_17GoogleSqlCollatorENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_PbPN4absl12lts_202601076StatusE(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32) int32 {
	return 0
}
func (h envStubs) X_ZN9googlesql9functions33StrPosOccurrenceUtf8WithCollationERKNS_17GoogleSqlCollatorENSt3__217basic_string_viewIcNS4_11char_traitsIcEEEES8_xxPxPN4absl12lts_202601076StatusE(m *base.Module, l0 int32, l1 int32, l2 int32, l3 int64, l4 int64, l5 int32, l6 int32) int32 {
	return 0
}
func (h envStubs) X_ZN9googlesql9functions6Hasher6CreateENS1_9AlgorithmE(m *base.Module, l0 int32) int32 {
	return 0
}
func (h envStubs) X__cxa_allocate_exception(m *base.Module, l0 int32) int32 {
	if l0 == 0 {
		l0 = 64
	}
	return wasm2go.WasmAlloc(m, l0)
}
func (h envStubs) X__cxa_throw(m *base.Module, l0 int32, l1 int32, l2 int32) {
	panic("wasm: C++ exception thrown")
}

var _ = fmt.Errorf
var _ = sort.Search

// cppTypeNames / cppTypeFactories: parallel sorted slices replacing
// the old cppTypeToGoType map literal. Looked up via sort.Search.
var cppTypeNames = []string{}

var cppTypeFactories = []func(uint64) any{}

// resolveAbstractHandle queries the C++ runtime for the actual type of the
// object at ptr and returns the appropriate concrete Go handle type.
func resolveAbstractHandle(ptr uint64) (any, error) {
	typeName, err := module().resolveTypeName(ptr)
	if err != nil {
		return nil, fmt.Errorf("resolveTypeName: %w", err)
	}
	i := sort.SearchStrings(cppTypeNames, typeName)
	if i < len(cppTypeNames) && cppTypeNames[i] == typeName {
		return cppTypeFactories[i](ptr), nil
	}
	return nil, fmt.Errorf("unknown C++ type %q for ptr 0x%x", typeName, ptr)
}

type ValidationError struct {
	Column         int32
	Line           int32
	Message        string
	StatementIndex int32
}

func (v *ValidationError) marshal() []byte {
	if v == nil {
		return nil
	}
	buf := pbNewBuf()
	buf = pbAppendInt32(buf, 1, v.Column)
	buf = pbAppendInt32(buf, 2, v.Line)
	buf = pbAppendString(buf, 3, v.Message)
	buf = pbAppendInt32(buf, 4, v.StatementIndex)
	return buf
}

func unmarshalValidationError(data []byte) *ValidationError {
	v := &ValidationError{}
	pr := &pbReader{data: data}
	for f, w, ok := pr.next(); ok; f, w, ok = pr.next() {
		switch f {
		case 1:
			v.Column = pr.readInt32()
		case 2:
			v.Line = pr.readInt32()
		case 3:
			v.Message = pr.readString()
		case 4:
			v.StatementIndex = pr.readInt32()
		default:
			pr.skip(w)
		}
	}
	return v
}

var _ = errors.New
var _ = fmt.Errorf
var _ = runtime.SetFinalizer

// Analyzes one query or DML statement (GoogleSQL dialect) against the schema
// the DDL statements describe, the way the emulator does before executing
// it: names are resolved against that schema's tables, columns, indexes and
// functions, and the statement is type checked. Returns an empty vector when
// the statement is valid.
//
// If the DDL itself does not build, that error is returned and the statement
// is not looked at. An error in the statement carries its 1-based line and
// column within `sql`; statement_index is always -1.
func AnalyzeQuery(ddls []string, sql string) ([]*ValidationError, error) {
	buf := pbNewBuf()
	for _, item := range ddls {
		buf = pbAppendString(buf, 1, item)
	}
	buf = pbAppendString(buf, 2, sql)
	resp, err := invokeMethod(0, 0, buf, wasm2go.Inv_0_0)
	if err != nil {
		return nil, err
	}
	var items []*ValidationError
	pr := &pbReader{data: resp}
	for f, w, ok := pr.next(); ok; f, w, ok = pr.next() {
		if f == 1 {
			sub := pr.readSubmessage()
			items = append(items, unmarshalValidationError(sub.data))
		} else {
			pr.skip(w)
		}
	}
	return items, nil
}

// Checks the syntax of each DDL statement (GoogleSQL dialect) with the
// emulator's DDL parser. Does not look at schema semantics, so every
// statement is checked independently and all errors are returned.
func ParseDDL(ddls []string) ([]*ValidationError, error) {
	buf := pbNewBuf()
	for _, item := range ddls {
		buf = pbAppendString(buf, 1, item)
	}
	resp, err := invokeMethod(0, 1, buf, wasm2go.Inv_0_1)
	if err != nil {
		return nil, err
	}
	var items []*ValidationError
	pr := &pbReader{data: resp}
	for f, w, ok := pr.next(); ok; f, w, ok = pr.next() {
		if f == 1 {
			sub := pr.readSubmessage()
			items = append(items, unmarshalValidationError(sub.data))
		} else {
			pr.skip(w)
		}
	}
	return items, nil
}

// Validates a whole set of DDL statements (GoogleSQL dialect) the way the
// emulator does for CreateDatabase: statements are applied in order to an
// empty schema and checked semantically (primary keys, interleaving,
// indexes, foreign keys, ...). Stops at the first error, like the emulator.
// Returns an empty vector when the DDL is valid.
func ValidateDDL(ddls []string) ([]*ValidationError, error) {
	buf := pbNewBuf()
	for _, item := range ddls {
		buf = pbAppendString(buf, 1, item)
	}
	resp, err := invokeMethod(0, 2, buf, wasm2go.Inv_0_2)
	if err != nil {
		return nil, err
	}
	var items []*ValidationError
	pr := &pbReader{data: resp}
	for f, w, ok := pr.next(); ok; f, w, ok = pr.next() {
		if f == 1 {
			sub := pr.readSubmessage()
			items = append(items, unmarshalValidationError(sub.data))
		} else {
			pr.skip(w)
		}
	}
	return items, nil
}
